//! FINDING-007: an embedded **CMYK JPEG** (Adobe APP14 / YCCK — what
//! Photoshop, ImageMagick and print workflows produce) must render with its
//! real colors, not as a solid black rectangle.
//!
//! The fixture `cmyk_adobe.jpg` is a solid `cmyk(200,30,30,0)` (cyan-ish)
//! 120×80 JPEG with an Adobe APP14 marker (transform 2 = YCCK), generated by
//! `magick -size 120x80 xc:'cmyk(200,30,30,0)' -colorspace CMYK cmyk.jpg`.
//!
//! Root cause: `jpeg-decoder` already resolves the APP14 transform and returns
//! TRUE CMYK, but the rasterizer inverted the samples again ("Adobe stores
//! inverted") — turning K = 0 into K = 1 → everything black. The PDF-side
//! embedding (`/DeviceCMYK` + inverting `/Decode`) was already correct: mutool
//! renders the same file cyan.

use pdf::Document;

const JPG: &[u8] = include_bytes!("fixtures/cmyk_adobe.jpg");

fn lic() {
    pdf::activate_license(
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../license/fixtures/dev_license.txt"
        ))
        .trim(),
    )
    .unwrap();
}

fn render_center() -> (u8, u8, u8) {
    let mut doc = Document::new();
    let id = doc.add_image_jpeg(JPG.to_vec()).unwrap();
    doc.add_page_sized(400.0, 300.0)
        .draw_image(id, 100.0, 100.0, 200.0, 130.0);
    let bytes = doc.to_bytes().unwrap();
    let page = pdf::render_page_rgba(&bytes, 0, 72.0).unwrap();
    // Center of the image rect (100..300 × 100..230 in PDF pts, y-flipped).
    let (px, py) = (200u32, (300 - 165) as u32);
    let off = ((py * page.width + px) * 4) as usize;
    (page.rgba[off], page.rgba[off + 1], page.rgba[off + 2])
}

#[test]
fn cmyk_jpeg_renders_cyan_not_black() {
    lic();
    let (r, g, b) = render_center();
    assert!(
        r < 100 && g > 150 && b > 150,
        "expected cyan-ish (low R, high G/B), got ({r},{g},{b})"
    );
}

/// The embedded PDF must keep `/DeviceCMYK` and the inverting `/Decode`
/// (Adobe storage) so external viewers interpret the verbatim JPEG correctly.
#[test]
fn cmyk_jpeg_embeds_devicecmyk_with_inverting_decode() {
    let mut doc = Document::new();
    let id = doc.add_image_jpeg(JPG.to_vec()).unwrap();
    doc.add_page_sized(400.0, 300.0)
        .draw_image(id, 100.0, 100.0, 200.0, 130.0);
    let raw = String::from_utf8_lossy(&doc.to_bytes().unwrap()).into_owned();
    assert!(raw.contains("/DeviceCMYK"), "CMYK color space missing");
    assert!(
        raw.contains("/Decode [1 0 1 0 1 0 1 0]") || raw.contains("/Decode[1 0 1 0 1 0 1 0]"),
        "inverting /Decode for Adobe CMYK missing: {}",
        raw.lines()
            .find(|l| l.contains("DCTDecode"))
            .unwrap_or("(no DCT line)")
    );
}
