// swift-tools-version:5.9
//
// RustPdf — idiomatic Swift binding for the rust-pdf core over its C ABI.
//
// This in-repo manifest links the dev build tree: it expects the native library
// at `<repo>/target/{debug,release}/libpdf_ffi.*` (build it with
// `cargo build -p pdf-ffi`). The *distributed* package instead consumes a
// prebuilt `.xcframework` (a static `libpdf_ffi.a` + headers) via a binary
// target — generated by `bindings/swift/scripts/package.sh` (`make swift-dist`).
import Foundation
import PackageDescription

// Locate the workspace root (the dir holding the top-level Cargo.toml) by
// walking up from this manifest, so the linker flags are absolute and stable
// regardless of the build's working directory.
func repoRoot() -> String {
    var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    for _ in 0..<12 {
        if FileManager.default.fileExists(atPath: dir.appendingPathComponent("Cargo.toml").path),
           FileManager.default.fileExists(atPath: dir.appendingPathComponent("crates").path) {
            return dir.path
        }
        let parent = dir.deletingLastPathComponent()
        if parent == dir { break }
        dir = parent
    }
    return dir.path
}

let root = repoRoot()

let package = Package(
    name: "RustPdf",
    platforms: [
        .macOS(.v11)
    ],
    products: [
        .library(name: "RustPdf", targets: ["RustPdf"]),
        .executable(name: "rustpdf-example", targets: ["Example"])
    ],
    targets: [
        // The C ABI declarations (a vendored copy of include/pdf.h).
        .target(
            name: "CRustPdf",
            path: "Sources/CRustPdf"
        ),
        .target(
            name: "RustPdf",
            dependencies: ["CRustPdf"],
            path: "Sources/RustPdf",
            linkerSettings: [
                // Link the native library from the dev build tree. The
                // distributed package replaces this with a binary xcframework.
                .unsafeFlags([
                    "-L\(root)/target/debug",
                    "-L\(root)/target/release"
                ]),
                .linkedLibrary("pdf_ffi"),
                .linkedLibrary("iconv")
            ]
        ),
        .executableTarget(
            name: "Example",
            dependencies: ["RustPdf"],
            path: "Sources/Example"
        ),
        .testTarget(
            name: "RustPdfTests",
            dependencies: ["RustPdf"],
            path: "Tests/RustPdfTests"
        )
    ]
)
